export default {
    customization: [],
    generateHTML: (options) => `
    <div class="body full flex column overflow-y-auto gap-5">
        <div class="body pt-4 pb-2 full">
            Akur Design System memiliki spektrum warna yang luas dan beragam, yang dapat diterapkan pada berbagai unsur visual dari setiap komponen, dengan pilihan intensitas warna yang bervariasi pada setiap kategori. Klik sebuah warna <b>untuk menyalin kode Hex</b>-nya.
        </div>
        <div class="body pt-2 pb-4 full flex column gap-5">
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Gray</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-0 tooltip onbody dark" data-color="#FAFAFA" data-colorname="Gray " data-tooltip="#FAFAFA" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-5 tooltip onbody dark" data-color="#F5F5F5" data-colorname="Gray " data-tooltip="#F5F5F5" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-10 tooltip onbody dark" data-color="#EFEFEF" data-colorname="Gray " data-tooltip="#EFEFEF" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-20 tooltip onbody dark" data-color="#D9DBDD" data-colorname="Gray " data-tooltip="#D9DBDD" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-30 tooltip onbody dark" data-color="#C9CBCF" data-colorname="Gray " data-tooltip="#C9CBCF" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-40 tooltip onbody dark" data-color="#B3B5B7" data-colorname="Gray " data-tooltip="#B3B5B7" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-50 tooltip onbody dark" data-color="#808489" data-colorname="Gray " data-tooltip="#808489" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-60 tooltip onbody dark" data-color="#65696C" data-colorname="Gray " data-tooltip="#65696C" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-70 tooltip onbody dark" data-color="#53575A" data-colorname="Gray " data-tooltip="#53575A" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-80 tooltip onbody dark" data-color="#45474A" data-colorname="Gray " data-tooltip="#45474A" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-90 tooltip onbody dark" data-color="#2F3031" data-colorname="Gray " data-tooltip="#2F3031" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-gray-100 tooltip onbody dark" data-color="#1E1F1F" data-colorname="Gray " data-tooltip="#1E1F1F" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Red</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-0 tooltip onbody dark" data-color="#FFFAFA" data-colorname="Red " data-tooltip="#FFFAFA" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-5 tooltip onbody dark" data-color="#FEF0F0" data-colorname="Red " data-tooltip="#FEF0F0" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-10 tooltip onbody dark" data-color="#FFE6E7" data-colorname="Red " data-tooltip="#FFE6E7" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-20 tooltip onbody dark" data-color="#FACCCF" data-colorname="Red " data-tooltip="#FACCCF" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-30 tooltip onbody dark" data-color="#FBB7BC" data-colorname="Red " data-tooltip="#FBB7BC" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-40 tooltip onbody dark" data-color="#F7979F" data-colorname="Red " data-tooltip="#F7979F" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-50 tooltip onbody dark" data-color="#ED5362" data-colorname="Red " data-tooltip="#ED5362" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-60 tooltip onbody dark" data-color="#E02D38" data-colorname="Red " data-tooltip="#E02D38" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-70 tooltip onbody dark" data-color="#C82228" data-colorname="Red " data-tooltip="#C82228" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-80 tooltip onbody dark" data-color="#AF182C" data-colorname="Red " data-tooltip="#AF182C" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-90 tooltip onbody dark" data-color="#70111D" data-colorname="Red " data-tooltip="#70111D" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-red-100 tooltip onbody dark" data-color="#3E0F15" data-colorname="Red " data-tooltip="#3E0F15" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Pink</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-0 tooltip onbody dark" data-color="#FEF6FA" data-colorname="Pink " data-tooltip="#FEF6FA" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-5 tooltip onbody dark" data-color="#FEECF4" data-colorname="Pink " data-tooltip="#FEECF4" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-10 tooltip onbody dark" data-color="#FFE1EF" data-colorname="Pink " data-tooltip="#FFE1EF" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-20 tooltip onbody dark" data-color="#FBC6E0" data-colorname="Pink " data-tooltip="#FBC6E0" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-30 tooltip onbody dark" data-color="#FAB2D6" data-colorname="Pink " data-tooltip="#FAB2D6" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-40 tooltip onbody dark" data-color="#F692C6" data-colorname="Pink " data-tooltip="#F692C6" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-50 tooltip onbody dark" data-color="#ED4A97" data-colorname="Pink " data-tooltip="#ED4A97" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-60 tooltip onbody dark" data-color="#D4307A" data-colorname="Pink " data-tooltip="#D4307A" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-70 tooltip onbody dark" data-color="#C41B63" data-colorname="Pink " data-tooltip="#C41B63" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-80 tooltip onbody dark" data-color="#B60C50" data-colorname="Pink " data-tooltip="#B60C50" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-90 tooltip onbody dark" data-color="#6E0D37" data-colorname="Pink " data-tooltip="#6E0D37" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-pink-100 tooltip onbody dark" data-color="#3E0E0E" data-colorname="Pink " data-tooltip="#3E0E0E" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Purple</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-0 tooltip onbody dark" data-color="#FBFAFF" data-colorname="Purple " data-tooltip="#FBFAFF" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-5 tooltip onbody dark" data-color="#F4F0FE" data-colorname="Purple " data-tooltip="#F4F0FE" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-10 tooltip onbody dark" data-color="#EBE6FF" data-colorname="Purple " data-tooltip="#EBE6FF" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-20 tooltip onbody dark" data-color="#DDD3FD" data-colorname="Purple " data-tooltip="#DDD3FD" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-30 tooltip onbody dark" data-color="#CFC1FB" data-colorname="Purple " data-tooltip="#CFC1FB" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-40 tooltip onbody dark" data-color="#BBA7F6" data-colorname="Purple " data-tooltip="#BBA7F6" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-50 tooltip onbody dark" data-color="#906CEF" data-colorname="Purple " data-tooltip="#906CEF" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-60 tooltip onbody dark" data-color="#7A47F0" data-colorname="Purple " data-tooltip="#7A47F0" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-70 tooltip onbody dark" data-color="#6B2FF9" data-colorname="Purple " data-tooltip="#6B2FF9" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-80 tooltip onbody dark" data-color="#5723CF" data-colorname="Purple " data-tooltip="#5723CF" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-90 tooltip onbody dark" data-color="#382166" data-colorname="Purple " data-tooltip="#382166" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-purple-100 tooltip onbody dark" data-color="#1E0F3D" data-colorname="Purple " data-tooltip="#1E0F3D" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Blue</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-0 tooltip onbody dark" data-color="#F6FAFE" data-colorname="Blue " data-tooltip="#F6FAFE" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-5 tooltip onbody dark" data-color="#ECF5FE" data-colorname="Blue " data-tooltip="#ECF5FE" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-10 tooltip onbody dark" data-color="#E1EFFE" data-colorname="Blue " data-tooltip="#E1EFFE" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-20 tooltip onbody dark" data-color="#CFE3FC" data-colorname="Blue " data-tooltip="#CFE3FC" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-30 tooltip onbody dark" data-color="#B1D1FB" data-colorname="Blue " data-tooltip="#B1D1FB" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-40 tooltip onbody dark" data-color="#91BCFD" data-colorname="Blue " data-tooltip="#91BCFD" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-50 tooltip onbody dark" data-color="#4C8DF6" data-colorname="Blue " data-tooltip="#4C8DF6" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-60 tooltip onbody dark" data-color="#2C70E5" data-colorname="Blue " data-tooltip="#2C70E5" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-70 tooltip onbody dark" data-color="#0B5FEF" data-colorname="Blue " data-tooltip="#0B5FEF" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-80 tooltip onbody dark" data-color="#054BCC" data-colorname="Blue " data-tooltip="#054BCC" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-90 tooltip onbody dark" data-color="#103178" data-colorname="Blue " data-tooltip="#103178" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-blue-100 tooltip onbody dark" data-color="#0E1C39" data-colorname="Blue " data-tooltip="#0E1C39" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Cyan</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-0 tooltip onbody dark" data-color="#F6FCFE" data-colorname="Cyan " data-tooltip="#F6FCFE" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-5 tooltip onbody dark" data-color="#E7F6FE" data-colorname="Cyan " data-tooltip="#E7F6FE" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-10 tooltip onbody dark" data-color="#DCF3FE" data-colorname="Cyan " data-tooltip="#DCF3FE" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-20 tooltip onbody dark" data-color="#C0E8FC" data-colorname="Cyan " data-tooltip="#C0E8FC" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-30 tooltip onbody dark" data-color="#9DDCFB" data-colorname="Cyan " data-tooltip="#9DDCFB" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-40 tooltip onbody dark" data-color="#74CBFB" data-colorname="Cyan " data-tooltip="#74CBFB" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-50 tooltip onbody dark" data-color="#3996ED" data-colorname="Cyan " data-tooltip="#3996ED" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-60 tooltip onbody dark" data-color="#1B7ADA" data-colorname="Cyan " data-tooltip="#1B7ADA" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-70 tooltip onbody dark" data-color="#0468CC" data-colorname="Cyan " data-tooltip="#0468CC" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-80 tooltip onbody dark" data-color="#125096" data-colorname="Cyan " data-tooltip="#125096" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-90 tooltip onbody dark" data-color="#103763" data-colorname="Cyan " data-tooltip="#103763" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-cyan-100 tooltip onbody dark" data-color="#082126" data-colorname="Cyan " data-tooltip="#082126" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Teal</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-0 tooltip onbody dark" data-color="#F1FEFE" data-colorname="Teal " data-tooltip="#F1FEFE" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-5 tooltip onbody dark" data-color="#DEFCFB" data-colorname="Teal " data-tooltip="#DEFCFB" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-10 tooltip onbody dark" data-color="#D2F9F8" data-colorname="Teal " data-tooltip="#D2F9F8" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-20 tooltip onbody dark" data-color="#B9EEEE" data-colorname="Teal " data-tooltip="#B9EEEE" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-30 tooltip onbody dark" data-color="#98E5E7" data-colorname="Teal " data-tooltip="#98E5E7" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-40 tooltip onbody dark" data-color="#6DD5D4" data-colorname="Teal " data-tooltip="#6DD5D4" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-50 tooltip onbody dark" data-color="#479CA1" data-colorname="Teal " data-tooltip="#479CA1" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-60 tooltip onbody dark" data-color="#347F7A" data-colorname="Teal " data-tooltip="#347F7A" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-70 tooltip onbody dark" data-color="#1E716B" data-colorname="Teal " data-tooltip="#1E716B" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-80 tooltip onbody dark" data-color="#165A57" data-colorname="Teal " data-tooltip="#165A57" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-90 tooltip onbody dark" data-color="#0D4241" data-colorname="Teal " data-tooltip="#0D4241" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-teal-100 tooltip onbody dark" data-color="#092524" data-colorname="Teal " data-tooltip="#092524" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Green</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-0 tooltip onbody dark" data-color="#F1FEF5" data-colorname="Green " data-tooltip="#F1FEF5" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-5 tooltip onbody dark" data-color="#E3FDEB" data-colorname="Green " data-tooltip="#E3FDEB" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-10 tooltip onbody dark" data-color="#CEFDE0" data-colorname="Green " data-tooltip="#CEFDE0" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-20 tooltip onbody dark" data-color="#BCF1D1" data-colorname="Green " data-tooltip="#BCF1D1" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-30 tooltip onbody dark" data-color="#A1E8BE" data-colorname="Green " data-tooltip="#A1E8BE" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-40 tooltip onbody dark" data-color="#7BD3A1" data-colorname="Green " data-tooltip="#7BD3A1" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-50 tooltip onbody dark" data-color="#4CA375" data-colorname="Green " data-tooltip="#4CA375" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-60 tooltip onbody dark" data-color="#2E8A5C" data-colorname="Green " data-tooltip="#2E8A5C" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-70 tooltip onbody dark" data-color="#117E47" data-colorname="Green " data-tooltip="#117E47" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-80 tooltip onbody dark" data-color="#04673A" data-colorname="Green " data-tooltip="#04673A" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-90 tooltip onbody dark" data-color="#084A2D" data-colorname="Green " data-tooltip="#084A2D" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-green-100 tooltip onbody dark" data-color="#092519" data-colorname="Green " data-tooltip="#092519" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Orange</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-0 tooltip onbody dark" data-color="#FFF9EE" data-colorname="Orange " data-tooltip="#FFF9EE" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-5 tooltip onbody dark" data-color="#FFEECE" data-colorname="Orange " data-tooltip="#FFEECE" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-10 tooltip onbody dark" data-color="#FFE0A5" data-colorname="Orange " data-tooltip="#FFE0A5" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-20 tooltip onbody dark" data-color="#FFD78A" data-colorname="Orange " data-tooltip="#FFD78A" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-30 tooltip onbody dark" data-color="#FABF4B" data-colorname="Orange " data-tooltip="#FABF4B" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-40 tooltip onbody dark" data-color="#EDA62B" data-colorname="Orange " data-tooltip="#EDA62B" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-50 tooltip onbody dark" data-color="#D99620" data-colorname="Orange " data-tooltip="#D99620" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-60 tooltip onbody dark" data-color="#B57F21" data-colorname="Orange " data-tooltip="#B57F21" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-70 tooltip onbody dark" data-color="#976A1C" data-colorname="Orange " data-tooltip="#976A1C" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-80 tooltip onbody dark" data-color="#815B18" data-colorname="Orange " data-tooltip="#815B18" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-90 tooltip onbody dark" data-color="#5F4212" data-colorname="Orange " data-tooltip="#5F4212" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-orange-100 tooltip onbody dark" data-color="#432C06" data-colorname="Orange " data-tooltip="#432C06" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Yellow</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-0 tooltip onbody dark" data-color="#FFFEEE" data-colorname="Yellow " data-tooltip="#FFFEEE" data-tooltip-position="top"></div><div class="body-sm">0</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-5 tooltip onbody dark" data-color="#FFFDCE" data-colorname="Yellow " data-tooltip="#FFFDCE" data-tooltip-position="top"></div><div class="body-sm">5</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-10 tooltip onbody dark" data-color="#FFFAAD" data-colorname="Yellow " data-tooltip="#FFFAAD" data-tooltip-position="top"></div><div class="body-sm">10</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-20 tooltip onbody dark" data-color="#FFF78A" data-colorname="Yellow " data-tooltip="#FFF78A" data-tooltip-position="top"></div><div class="body-sm">20</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-30 tooltip onbody dark" data-color="#FAF44B" data-colorname="Yellow " data-tooltip="#FAF44B" data-tooltip-position="top"></div><div class="body-sm">30</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-40 tooltip onbody dark" data-color="#EDE500" data-colorname="Yellow " data-tooltip="#EDE500" data-tooltip-position="top"></div><div class="body-sm">40</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-50 tooltip onbody dark" data-color="#D7D004" data-colorname="Yellow " data-tooltip="#D7D004" data-tooltip-position="top"></div><div class="body-sm">50</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-60 tooltip onbody dark" data-color="#BEB804" data-colorname="Yellow " data-tooltip="#BEB804" data-tooltip-position="top"></div><div class="body-sm">60</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-70 tooltip onbody dark" data-color="#A5A003" data-colorname="Yellow " data-tooltip="#A5A003" data-tooltip-position="top"></div><div class="body-sm">70</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-80 tooltip onbody dark" data-color="#7D7903" data-colorname="Yellow " data-tooltip="#7D7903" data-tooltip-position="top"></div><div class="body-sm">80</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-90 tooltip onbody dark" data-color="#646002" data-colorname="Yellow " data-tooltip="#646002" data-tooltip-position="top"></div><div class="body-sm">90</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-yellow-100 tooltip onbody dark" data-color="#3A3900" data-colorname="Yellow " data-tooltip="#3A3900" data-tooltip-position="top"></div><div class="body-sm">100</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Neutral</div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-black tooltip onbody dark" data-color="#000000" data-colorname="" ddata-tooltip="#000000" data-tooltip-position="top"></div><div class="body-sm">Black</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 surface-white tooltip onbody dark" data-color="#FFFFFF" data-colorname="" data-tooltip="#FFFFFF" data-tooltip-position="top"></div><div class="body-sm">White</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
        </div>
        <div class="body pt-4 pb-2 full">
            Dari spektrum warna yang tersedia, diturunkan beberapa warna yang digunakan pada unsur komponen, seperti warna <i>text</i>, <i>icon</i>, <i>border</i>, <i>surface</i>, <i>base</i>, <i>action</i>, dan <i>interactive</i>.
        </div>
        <div class="body pt-2 pb-4 full flex column gap-5">
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Text</div>
            </div>
            <div class="grid grid-5 gap-4">
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#2F3031" data-colorname="Text " data-tooltip="gray-90" data-tooltip-position="top" style="background: var(--text-default);"></div><div class="eyebrow-sm">Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#65696C" data-colorname="Text " data-tooltip="gray-60" data-tooltip-position="top" style="background: var(--text-subdued);"></div><div class="eyebrow-sm">Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#808489" data-colorname="Text " data-tooltip="gray-50" data-tooltip-position="top" style="background: var(--text-disabled);"></div><div class="eyebrow-sm">Disabled</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#FFFFFF" data-colorname="Text " data-tooltip="white" data-tooltip-position="top" style="background: var(--text-inverse);"></div><div class="eyebrow-sm">Inverse</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#D9DBDD" data-colorname="Text " data-tooltip="gray-20" data-tooltip-position="top" style="background: var(--text-inverse-subdued);"></div><div class="eyebrow-sm">Inverse Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#2E8A5C" data-colorname="Text " data-tooltip="green-60" data-tooltip-position="top" style="background: var(--text-success);"></div><div class="eyebrow-sm">Success</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#04673A" data-colorname="Text " data-tooltip="green-80" data-tooltip-position="top" style="background: var(--text-success-darker);"></div><div class="eyebrow-sm">Success Darker</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#E02D38" data-colorname="Text " data-tooltip="red-60" data-tooltip-position="top" style="background: var(--text-informational);"></div><div class="eyebrow-sm">Informational</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#AF182C" data-colorname="Text " data-tooltip="red-80" data-tooltip-position="top" style="background: var(--text-informational-darker);"></div><div class="eyebrow-sm">Informational Darker</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#1B7ADA" data-colorname="Text " data-tooltip="cyan-60" data-tooltip-position="top" style="background: var(--text-warning);"></div><div class="eyebrow-sm">Warning</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#125096" data-colorname="Text " data-tooltip="cyan-80" data-tooltip-position="top" style="background: var(--text-warning-darker);"></div><div class="eyebrow-sm">Warning Darker</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#976A1C" data-colorname="Text " data-tooltip="orange-70" data-tooltip-position="top" style="background: var(--text-critical);"></div><div class="eyebrow-sm">Critical</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#815B18" data-colorname="Text " data-tooltip="orange-80" data-tooltip-position="top" style="background: var(--text-critical-darker);"></div><div class="eyebrow-sm">Critical Darker</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Icon</div>
            </div>
            <div class="grid grid-5 gap-4">
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#45474A" data-colorname="Icon " data-tooltip="gray-80" data-tooltip-position="top" style="background: var(--icon-default);"></div><div class="eyebrow-sm">Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#808489" data-colorname="Icon " data-tooltip="gray-50" data-tooltip-position="top" style="background: var(--icon-subdued);"></div><div class="eyebrow-sm">Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#2F3031" data-colorname="Icon " data-tooltip="gray-90" data-tooltip-position="top" style="background: var(--icon-hovered);"></div><div class="eyebrow-sm">Hovered</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#1E1F1F" data-colorname="Icon " data-tooltip="gray-100" data-tooltip-position="top" style="background: var(--icon-pressed);"></div><div class="eyebrow-sm">Pressed</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#B3B5B7" data-colorname="Icon " data-tooltip="gray-40" data-tooltip-position="top" style="background: var(--icon-disabled);"></div><div class="eyebrow-sm">Disabled</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#F5F5F5" data-colorname="Icon " data-tooltip="gray-5" data-tooltip-position="top" style="background: var(--icon-inverse);"></div><div class="eyebrow-sm">Inverse</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#4CA375" data-colorname="Icon " data-tooltip="green-50" data-tooltip-position="top" style="background: var(--icon-success);"></div><div class="eyebrow-sm">Success</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#E02D38" data-colorname="Icon " data-tooltip="red-60" data-tooltip-position="top" style="background: var(--icon-informational);"></div><div class="eyebrow-sm">Informational</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#125096" data-colorname="Icon " data-tooltip="cyan-80" data-tooltip-position="top" style="background: var(--icon-warning);"></div><div class="eyebrow-sm">Warning</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#D99620" data-colorname="Icon " data-tooltip="orange-50" data-tooltip-position="top" style="background: var(--icon-critical);"></div><div class="eyebrow-sm">Critical</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Border</div>
            </div>
            <div class="grid grid-5 gap-4">
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#53575A" data-colorname="Border " data-tooltip="gray-70" data-tooltip-position="top" style="background: var(--border-default);"></div><div class="eyebrow-sm">Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#808489" data-colorname="Border " data-tooltip="gray-50" data-tooltip-position="top" style="background: var(--border-high);"></div><div class="eyebrow-sm">High</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#C9CBCF" data-colorname="Border " data-tooltip="gray-30" data-tooltip-position="top" style="background: var(--border-subdued);"></div><div class="eyebrow-sm">Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#D9DBDD" data-colorname="Border " data-tooltip="gray-20" data-tooltip-position="top" style="background: var(--border-disabled);"></div><div class="eyebrow-sm">Disabled</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#45474A" data-colorname="Border " data-tooltip="gray-80" data-tooltip-position="top" style="background: var(--border-hovered);"></div><div class="eyebrow-sm">Hovered</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#1E1F1F" data-colorname="Border " data-tooltip="gray-100" data-tooltip-position="top" style="background: var(--border-pressed);"></div><div class="eyebrow-sm">Pressed</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#4CA375" data-colorname="Border " data-tooltip="green-50" data-tooltip-position="top" style="background: var(--border-success);"></div><div class="eyebrow-sm">Success</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#E02D38" data-colorname="Border " data-tooltip="red-60" data-tooltip-position="top" style="background: var(--border-critical);"></div><div class="eyebrow-sm">Critical</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#3996ED" data-colorname="Border " data-tooltip="cyan-50" data-tooltip-position="top" style="background: var(--border-informational);"></div><div class="eyebrow-sm">Informational</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#EDA62B" data-colorname="Border " data-tooltip="orange-40" data-tooltip-position="top" style="background: var(--border-warning);"></div><div class="eyebrow-sm">Warning</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Surface</div>
            </div>
            <div class="grid grid-5 gap-4">
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#FFFFFF" data-colorname="Surface " data-tooltip="white" data-tooltip-position="top" style="background: var(--surface-default);"></div><div class="eyebrow-sm">Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#F5F5F5" data-colorname="Surface " data-tooltip="gray-5" data-tooltip-position="top" style="background: var(--surface-subdued);"></div><div class="eyebrow-sm">Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#EFEFEF" data-colorname="Surface " data-tooltip="gray-10" data-tooltip-position="top" style="background: var(--surface-hovered);"></div><div class="eyebrow-sm">Hovered</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#EFEFEF" data-colorname="Surface " data-tooltip="gray-10" data-tooltip-position="top" style="background: var(--surface-disabled);"></div><div class="eyebrow-sm">Disabled</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#2F3031" data-colorname="Surface " data-tooltip="gray-90" data-tooltip-position="top" style="background: var(--surface-foreground);"></div><div class="eyebrow-sm">Foreground</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#D9DBDD" data-colorname="Surface " data-tooltip="gray-20" data-tooltip-position="top" style="background: var(--surface-pressed);"></div><div class="eyebrow-sm">Pressed</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#EFEFEF" data-colorname="Surface " data-tooltip="gray-10" data-tooltip-position="top" style="background: var(--surface-selected-default);"></div><div class="eyebrow-sm">Selected Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#C9CBCF" data-colorname="Surface " data-tooltip="gray-30" data-tooltip-position="top" style="background: var(--surface-selected-hovered);"></div><div class="eyebrow-sm">Selected Hovered</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#D9DBDD" data-colorname="Surface " data-tooltip="gray-20" data-tooltip-position="top" style="background: var(--surface-neutral-default);"></div><div class="eyebrow-sm">Neutral Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#EFEFEF" data-colorname="Surface " data-tooltip="gray-10" data-tooltip-position="top" style="background: var(--surface-neutral-subdued);"></div><div class="eyebrow-sm">Neutral Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#A1E8BE" data-colorname="Surface " data-tooltip="green-30" data-tooltip-position="top" style="background: var(--surface-success-default);"></div><div class="eyebrow-sm">Success Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#E3FDEB" data-colorname="Surface " data-tooltip="green-5" data-tooltip-position="top" style="background: var(--surface-success-subdued);"></div><div class="eyebrow-sm">Success Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#084A2D" data-colorname="Surface " data-tooltip="green-90" data-tooltip-position="top" style="background: var(--surface-success-darker);"></div><div class="eyebrow-sm">Success Darker</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#FFE6E7" data-colorname="Surface " data-tooltip="red-10" data-tooltip-position="top" style="background: var(--surface-critical-default);"></div><div class="eyebrow-sm">Critical Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#FEF0F0" data-colorname="Surface " data-tooltip="red-5" data-tooltip-position="top" style="background: var(--surface-critical-subdued);"></div><div class="eyebrow-sm">Critical Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#70111D" data-colorname="Surface " data-tooltip="red-90" data-tooltip-position="top" style="background: var(--surface-critical-darker);"></div><div class="eyebrow-sm">Critical Darker</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#9DDCFB" data-colorname="Surface " data-tooltip="cyan-30" data-tooltip-position="top" style="background: var(--surface-informational-default);"></div><div class="eyebrow-sm">Informational Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#E7F6FE" data-colorname="Surface " data-tooltip="cyan-5" data-tooltip-position="top" style="background: var(--surface-informational-subdued);"></div><div class="eyebrow-sm">Informational Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#103763" data-colorname="Surface " data-tooltip="cyan-90" data-tooltip-position="top" style="background: var(--surface-informational-darker);"></div><div class="eyebrow-sm">Informational Darker</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#FFD78A" data-colorname="Surface " data-tooltip="orange-20" data-tooltip-position="top" style="background: var(--surface-warning-default);"></div><div class="eyebrow-sm">Warning Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#FFE0A5" data-colorname="Surface " data-tooltip="orange-10" data-tooltip-position="top" style="background: var(--surface-warning-subdued);"></div><div class="eyebrow-sm">Warning Subdued</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#5F4212" data-colorname="Surface " data-tooltip="orange-90" data-tooltip-position="top" style="background: var(--surface-warning-darker);"></div><div class="eyebrow-sm">Warning Darker</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Base</div>
            </div>
            <div class="grid grid-5 gap-4">
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#0468CC" data-colorname="Base " data-tooltip="cyan-70" data-tooltip-position="top" style="background: var(--base-primary);"></div><div class="eyebrow-sm">Primary</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#2E8A5C" data-colorname="Base " data-tooltip="green-60" data-tooltip-position="top" style="background: var(--base-success);"></div><div class="eyebrow-sm">Success</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#C82228" data-colorname="Base " data-tooltip="red-70" data-tooltip-position="top" style="background: var(--base-critical);"></div><div class="eyebrow-sm">Critical</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#3996ED" data-colorname="Base " data-tooltip="cyan-50" data-tooltip-position="top" style="background: var(--base-informational);"></div><div class="eyebrow-sm">Informational</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#FABF4B" data-colorname="Base " data-tooltip="orange-30" data-tooltip-position="top" style="background: var(--base-warning);"></div><div class="eyebrow-sm">Warning</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Action</div>
            </div>
            <div class="grid grid-5 gap-4">
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#0468CC" data-colorname="Action " data-tooltip="cyan-70" data-tooltip-position="top" style="background: var(--action-default);"></div><div class="eyebrow-sm">Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#125096" data-colorname="Action " data-tooltip="cyan-80" data-tooltip-position="top" style="background: var(--action-hovered);"></div><div class="eyebrow-sm">Hovered</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#103763" data-colorname="Action " data-tooltip="cyan-90" data-tooltip-position="top" style="background: var(--action-pressed);"></div><div class="eyebrow-sm">Pressed</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#C9CBCF" data-colorname="Action " data-tooltip="gray-30" data-tooltip-position="top" style="background: var(--action-disabled);"></div><div class="eyebrow-sm">Disabled</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#2F3031" data-colorname="Action " data-tooltip="gray-90" data-tooltip-position="top" style="background: var(--action-neutral-default);"></div><div class="eyebrow-sm">Neutral Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#1E1F1F" data-colorname="Action " data-tooltip="gray-100" data-tooltip-position="top" style="background: var(--action-neutral-hovered);"></div><div class="eyebrow-sm">Neutral Hovered</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#000000" data-colorname="Action " data-tooltip="black" data-tooltip-position="top" style="background: var(--action-neutral-pressed);"></div><div class="eyebrow-sm">Neutral Pressed</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
            <div class="flex row gap-4">
                <div class="heading-md color-title">Interactive</div>
            </div>
            <div class="grid grid-5 gap-4">
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#0468CC" data-colorname="Interactive " data-tooltip="cyan-70" data-tooltip-position="top" style="background: var(--interactive-default);"></div><div class="eyebrow-sm">Default</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#125096" data-colorname="Interactive " data-tooltip="cyan-80" data-tooltip-position="top" style="background: var(--interactive-hovered);"></div><div class="eyebrow-sm">Hovered</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#3996ED" data-colorname="Interactive " data-tooltip="cyan-50" data-tooltip-position="top" style="background: var(--interactive-focused);"></div><div class="eyebrow-sm">Focused</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#C9CBCF" data-colorname="Interactive " data-tooltip="gray-30" data-tooltip-position="top" style="background: var(--interactive-disabled);"></div><div class="eyebrow-sm">Disabled</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#74CBFB" data-colorname="Interactive " data-tooltip="cyan-40" data-tooltip-position="top" style="background: var(--interactive-foreground);"></div><div class="eyebrow-sm">Foreground</div></div>
                <div class="flex column full gap-2"><div class="color-box rounded-8 elevation-1 tooltip onbody dark" data-color="#E02D38" data-colorname="Interactive " data-tooltip="red-60" data-tooltip-position="top" style="background: var(--interactive-critical);"></div><div class="eyebrow-sm">Critical</div></div>
            </div>
            <div class="separator-1 vertical border-color-disabled"></div>
        </div>
    </div>
    `
};